FROM python:3.9-slim
ENV PROJECT_NAME="WareHouse"
ENV VERSION="1..0"
ENV DESCRIPTION=""
ENV DATABASE_URL="sqlite+aiosqlite:///./data.db"
ENV ECHO_SQL="False"
ENV API_KEY="apnarasimhareddy"

WORKDIR /app

COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

COPY . /app/

EXPOSE 8000

# Command to run the FastAPI application using Uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]